apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-demo
  labels:
    app: argo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-demo
  template:
    metadata:
      labels:
        app: argo-demo
    spec:
      containers:
        - name: argo-demo
          image: docker.io/fev1n/argo-demo:latest
          ports:
            - containerPort: 8080
